import { mkdir, readdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { join } from "node:path";
import { artifactChecksum } from "../artifacts/validation.js";

export type SkillCategory = "core" | "routable";
export type SkillRole = "primary" | "auxiliary";
export interface PublishedSkill { slug:string; versionId:number; version:number; checksum:string; body:unknown; ownerId?:number|null; status?:string; score?:number }
export interface Skill { id:string; text:string; versionId:number; version:number; checksum:string; purpose:string; applicability:string; order:number; safety:boolean; tenantId:number|null; triggers:string[]; role:SkillRole; category:SkillCategory; score?:number }
export interface SkillRegistry { publishedSkills(environment:string, subject:string):Promise<PublishedSkill[]> }
export interface SkillError { code:"skill_invalid"|"skill_registry_failed"|"safety_budget_exceeded"; skill?:string }

export function parseSkill(row:PublishedSkill):Skill|null {
  const b=row.body as Record<string,unknown>;
  if (!b || typeof b!=="object" || typeof b.name!=="string" || typeof b.source!=="string" || typeof b.purpose!=="string" || typeof b.applicability!=="string" || !Number.isInteger(b.order) || !(b.category==="core"||b.category==="routable") || !(b.role==="primary"||b.role==="auxiliary") || "tools" in b || "code" in b || "executable" in b) return null;
  const checksum=artifactChecksum(b); if(row.checksum && row.checksum!==checksum) return null;
  return {id:row.slug,text:b.source,versionId:row.versionId,version:row.version,checksum:row.checksum||checksum,purpose:b.purpose,applicability:b.applicability,order:Number(b.order),safety:b.safety===true,tenantId:row.ownerId??(typeof b.tenantId==="number"?b.tenantId:null),triggers:Array.isArray(b.triggers)?b.triggers.filter((x):x is string=>typeof x==="string"):[],role:b.role,category:b.category,score:row.score};
}

export class CoreSkillCatalog {
  constructor(private registry:SkillRegistry,private options:{enabled:boolean;maxCharacters?:number;safetyMaxCharacters?:number;onError?:(e:SkillError)=>void}){}
  async load(environment:string,subject:string){
    if(!this.options.enabled) return {skills:[] as Skill[],index:"",characters:0,versionIds:[] as number[]};
    let rows:PublishedSkill[]; try { rows=await this.registry.publishedSkills(environment,subject); } catch { this.options.onError?.({code:"skill_registry_failed"}); return {skills:[],index:"",characters:0,versionIds:[]}; }
    const all=rows.map(parseSkill).filter((x):x is Skill=>!!x&&x.category==="core").sort((a,b)=>Number(b.safety)-Number(a.safety)||a.order-b.order||a.id.localeCompare(b.id)).slice(0,12);
    const safety=all.filter(x=>x.safety); const safetyChars=safety.reduce((n,x)=>n+x.text.length,0); const safetyLimit=this.options.safetyMaxCharacters??4000;
    if(!safety.length || safetyChars>safetyLimit){ this.options.onError?.({code:"safety_budget_exceeded",skill:safety[0]?.id}); return {skills:[],index:"01 immutable-safe-baseline | safety boundaries | always | v1",characters:59,versionIds:[],featureEnabled:false}; }
    const fitted=[...safety]; const limit=this.options.maxCharacters??12000;
    for(const s of all.filter(x=>!x.safety)){const next=fitted.concat(s); if(next.reduce((n,x)=>n+x.text.length,0)+makeIndex(next).length<=limit) fitted.push(s);}
    const index=makeIndex(fitted); return {skills:fitted,index,characters:index.length+fitted.reduce((n,s)=>n+s.text.length,0),versionIds:fitted.map(s=>s.versionId),featureEnabled:true};
  }
}
const makeIndex=(s:Skill[])=>s.map((x,i)=>`${String(i+1).padStart(2,"0")} ${x.id} | ${x.purpose} | ${x.applicability} | v${x.version}`).join("\n");
const topicFingerprint=(skill:Skill)=>createHash("sha256").update(JSON.stringify([skill.id,skill.versionId,skill.triggers,skill.purpose,skill.applicability])).digest("hex");
const ACKNOWLEDGEMENTS=new Set(["да","ага","угу","ок","окей","хорошо","продолжай","дальше","понятно","согласен","согласна"]);
const isShortFollowup=(message:string)=>ACKNOWLEDGEMENTS.has(message.normalize("NFKC").toLocaleLowerCase("ru-RU").trim().replace(/[.!?,;:]+$/u,"").trim());

export interface SkillState {skill:Skill;topicFingerprint:string;scenarioState:"active"|"completed";turns:number;expiresAt:number}
export interface SkillRepository extends SkillRegistry {loadState(userId:number,conversationId:string):Promise<SkillState|null>;saveState(userId:number,conversationId:string,state:SkillState):Promise<void>;clearState(userId:number,conversationId:string,reason:string):Promise<void>;hybridSearch(input:{tenantId:number;environment:string;query:string;vector?:number[];limit:number}):Promise<PublishedSkill[]>;recordEvent(event:Record<string,unknown>):Promise<void>;recordUsage?(runId:string,versionIds:number[]):Promise<void>}
export interface RouteInput {tenantId:number;conversationId:string;runId?:string;turnId?:string;purpose:string;message:string;scenarioComplete?:boolean}
export class SkillRouter {
 constructor(private repo:SkillRepository,private options:{enabled:boolean;environment?:string;maxCharacters?:number;stickyTurns?:number;stickyTtlMs?:number;embed?:(text:string)=>Promise<number[]>;rerank?:(c:Array<Pick<Skill,"id"|"purpose"|"applicability">>)=>Promise<string[]>;rerankCloseScore?:number;lowConfidence?:number;observe?:(x:{reason:string;latencyMs:number;reranked:boolean})=>void}){}
 async route(i:RouteInput){
  const started=performance.now(); if(!this.options.enabled)return this.finish(i,[],false,true,"disabled",started,false);
  try {
   const prior=await this.repo.loadState(i.tenantId,i.conversationId);
   if(prior&&i.scenarioComplete){await this.repo.clearState(i.tenantId,i.conversationId,"scenario_completed");return this.finish(i,[],false,false,"completed",started,false);}
   const boundary=prior&&(prior.scenarioState==="completed"||prior.expiresAt<=Date.now()||prior.turns>=(this.options.stickyTurns??8));
   if(boundary) await this.repo.clearState(i.tenantId,i.conversationId,"boundary");
   else if(prior&&isShortFollowup(i.message)){const next={...prior,turns:prior.turns+1,expiresAt:Date.now()+(this.options.stickyTtlMs??900000)};await this.repo.saveState(i.tenantId,i.conversationId,next);return this.finish(i,[prior.skill],true,false,"active",started,false);}
   let rows=await this.repo.publishedSkills(this.options.environment??"production",String(i.tenantId)); let pool=rows.map(parseSkill).filter((s):s is Skill=>!!s&&s.category==="routable"&&!s.safety&&(s.tenantId===null||s.tenantId===i.tenantId));
   const triggered=pool.filter(s=>s.triggers.some(t=>i.message.toLowerCase().includes(t.toLowerCase()))); let reason="trigger";
   if(triggered.length)pool=triggered; else {reason="hybrid";const vector=this.options.embed?await this.options.embed(i.message):undefined;rows=await this.repo.hybridSearch({tenantId:i.tenantId,environment:this.options.environment??"production",query:i.message,vector,limit:10});pool=rows.map(parseSkill).filter((s):s is Skill=>!!s&&s.category==="routable"&&!s.safety&&(s.tenantId===null||s.tenantId===i.tenantId));}
   let reranked=false; const scores=pool.map(x=>x.score??0); const close=scores.length>1&&Math.abs(scores[0]!-scores[1]!)<=(this.options.rerankCloseScore??.08), low=(scores[0]??0)<(this.options.lowConfidence??.35);
   if(this.options.rerank&&pool.length&&(close||low)){const ids=await this.options.rerank(pool.map(({id,purpose,applicability})=>({id,purpose,applicability})));const rank=new Map(ids.map((id,n)=>[id,n]));pool.sort((a,b)=>(rank.get(a.id)??Number.MAX_SAFE_INTEGER)-(rank.get(b.id)??Number.MAX_SAFE_INTEGER));reranked=true;}
   const primary=pool.find(x=>x.role==="primary"); const aux=pool.filter(x=>x.role==="auxiliary"&&x.id!==primary?.id).slice(0,2); const selected=[...(primary?[primary]:[]),...aux].slice(0,3); let used=0;const fitted=selected.filter(x=>{if(used+x.text.length>(this.options.maxCharacters??12000))return false;used+=x.text.length;return true;});
   const fingerprint=fitted[0]?topicFingerprint(fitted[0]):"";
   if(prior&&!boundary&&fingerprint===prior.topicFingerprint){const next={...prior,turns:prior.turns+1,expiresAt:Date.now()+(this.options.stickyTtlMs??900000)};await this.repo.saveState(i.tenantId,i.conversationId,next);return this.finish(i,[prior.skill],true,false,"active",started,reranked);}
   if(prior&&!boundary)await this.repo.clearState(i.tenantId,i.conversationId,"topic_changed");
   if(fitted[0])await this.repo.saveState(i.tenantId,i.conversationId,{skill:fitted[0],topicFingerprint:fingerprint,scenarioState:"active",turns:1,expiresAt:Date.now()+(this.options.stickyTtlMs??900000)});
   return this.finish(i,fitted,false,false,reason,started,reranked);
  } catch { return this.finish(i,[],false,true,"error",started,false); }
 }
 completeScenario(i:Omit<RouteInput,"message"|"scenarioComplete">){return this.route({...i,message:"",scenarioComplete:true});}
 private async finish(i:RouteInput,selected:Skill[],sticky:boolean,fallback:boolean,reason:string,started:number,reranked:boolean){const latencyMs=performance.now()-started;this.options.observe?.({reason,latencyMs,reranked});try{await this.repo.recordEvent({userId:i.tenantId,conversationId:i.conversationId,selected:selected.map(x=>({id:x.id,version_id:x.versionId,version:x.version,score:x.score??null})),reason,sticky,fallback,reranked,latencyMs});}catch{ /* telemetry is best-effort */ }if(i.runId&&selected.length)try{await this.repo.recordUsage?.(i.runId,selected.map(x=>x.versionId));}catch{ /* usage is best-effort */ }return{selected,sticky,fallback,reason};}
}

export class FilesystemSkillIndexer {readonly agentRecreations=0;private running:Promise<{active:number;disabled:number}>|null=null;private pending=false;constructor(private sink:{syncIndexedSkill(x:Record<string,unknown>):Promise<void>},private options:{root:string;environment:string;runtimeRoot?:string}){} sync(){if(this.running){this.pending=true;return this.running;}this.running=this.runLoop().finally(()=>{this.running=null});return this.running;}private async runLoop(){let result={active:0,disabled:0};do{this.pending=false;result=await this.runOnce();}while(this.pending);return result;}private async runOnce(){let active=0,disabled=0;const staged:Array<{slug:string;raw:string}>=[];for(const ent of await readdir(this.options.root,{withFileTypes:true})){if(!ent.isDirectory())continue;const slug=ent.name;try{const raw=await readFile(join(this.options.root,slug,"SKILL.md"),"utf8");const m=/^---\n([\s\S]*?)\n---\n([\s\S]*)$/u.exec(raw);if(!m)throw new Error("frontmatter_missing");const meta=Object.fromEntries(m[1]!.split("\n").map(l=>{const p=l.indexOf(":");return[l.slice(0,p).trim(),l.slice(p+1).trim()] }));if(!["core","routable"].includes(meta.category!)||!["primary","auxiliary"].includes(meta.role!))throw new Error("metadata_invalid");const body={...meta,source:m[2]!,order:Number(meta.order),safety:meta.safety==="true",triggers:meta.triggers?meta.triggers.split(",").map(x=>x.trim()):[]};await this.sink.syncIndexedSkill({slug,environment:this.options.environment,checksum:artifactChecksum(body),body,status:"active",error:null});staged.push({slug,raw});active++;}catch(e){await this.sink.syncIndexedSkill({slug,environment:this.options.environment,checksum:null,status:"disabled",error:e instanceof Error?e.message:"invalid"});disabled++;}}if(this.options.runtimeRoot){const accepted=new Set(staged.map(s=>s.slug));for(const s of staged){const dir=join(this.options.runtimeRoot,s.slug);await mkdir(dir,{recursive:true});const next=join(dir,`.SKILL.md.next-${process.pid}`);await writeFile(next,s.raw,{mode:0o444});await rename(next,join(dir,"SKILL.md"));}for(const ent of await readdir(this.options.runtimeRoot,{withFileTypes:true}))if(ent.isDirectory()&&!accepted.has(ent.name))await rm(join(this.options.runtimeRoot,ent.name),{recursive:true,force:true});}return{active,disabled};}}

export class PostgresSkillRepository implements SkillRepository {
 constructor(private db:{query(sql:string,values?:unknown[]):Promise<{rows:Record<string,unknown>[];rowCount?:number|null}>}){}
 async publishedSkills(environment:string,subject:string){const{rows}=await this.db.query("SELECT slug,version_id,version,checksum,body,owner_user_id,status FROM skill_search_index WHERE environment=$1 AND status='active' AND category='routable' AND (owner_user_id IS NULL OR owner_user_id=$2::bigint)",[environment,Number(subject)]);return rows.map(rowSkill);}
 async loadState(u:number,c:string){const{rows}=await this.db.query("SELECT s.*,i.slug,i.version,i.checksum,i.body,i.owner_user_id,i.status FROM skill_routing_state s JOIN skill_search_index i ON i.version_id=s.skill_version_id WHERE s.user_id=$1 AND s.conversation_id=$2",[u,c]);const r=rows[0];if(!r)return null;const skill=parseSkill(rowSkill(r));return skill?{skill,topicFingerprint:String(r.topic_fingerprint),scenarioState:String(r.scenario_state) as "active"|"completed",turns:Number(r.turns),expiresAt:new Date(String(r.expires_at)).getTime()}:null;}
 async saveState(u:number,c:string,s:SkillState){await this.db.query("INSERT INTO skill_routing_state(user_id,conversation_id,skill_version_id,topic_fingerprint,scenario_state,turns,expires_at) VALUES($1,$2,$3,$4,$5,$6,to_timestamp($7/1000.0)) ON CONFLICT(user_id,conversation_id) DO UPDATE SET skill_version_id=$3,topic_fingerprint=$4,scenario_state=$5,turns=$6,expires_at=to_timestamp($7/1000.0),updated_at=now()",[u,c,s.skill.versionId,s.topicFingerprint,s.scenarioState,s.turns,s.expiresAt]);}
 async clearState(u:number,c:string,_r:string){await this.db.query("DELETE FROM skill_routing_state WHERE user_id=$1 AND conversation_id=$2",[u,c]);}
 async hybridSearch(x:{tenantId:number;environment:string;query:string;vector?:number[];limit:number}){const limit=Math.max(1,Math.min(20,Math.trunc(x.limit)));const q=x.query.slice(0,500);let sql:string;let values:unknown[];if(x.vector!==undefined){if(x.vector.length!==1536||x.vector.some(n=>!Number.isFinite(n)))throw new Error("embedding must have exactly 1536 finite dimensions");sql="SELECT slug,version_id,version,checksum,body,owner_user_id,status,GREATEST(ts_rank(search_document,websearch_to_tsquery('simple',$3)),similarity(search_text,$3),1-(embedding <=> $4::vector)) AS score FROM skill_search_index WHERE environment=$1 AND status='active' AND category='routable' AND (owner_user_id IS NULL OR owner_user_id=$2) ORDER BY score DESC LIMIT $5";values=[x.environment,x.tenantId,q,`[${x.vector.join(",")}]`,limit];}else{sql="SELECT slug,version_id,version,checksum,body,owner_user_id,status,GREATEST(ts_rank(search_document,websearch_to_tsquery('simple',$3)),similarity(search_text,$3)) AS score FROM skill_search_index WHERE environment=$1 AND status='active' AND category='routable' AND (owner_user_id IS NULL OR owner_user_id=$2) ORDER BY score DESC LIMIT $4";values=[x.environment,x.tenantId,q,limit];}const{rows}=await this.db.query(sql,values);return rows.map(rowSkill);}
 async recordEvent(e:Record<string,unknown>){await this.db.query("INSERT INTO skill_routing_events(user_id,conversation_id,selected,reason_code,sticky,fallback,reranker_called,latency_ms) VALUES($1,$2,$3::jsonb,$4,$5,$6,$7,$8)",[e.userId,e.conversationId,JSON.stringify(e.selected),e.reason,e.sticky,e.fallback,e.reranked,e.latencyMs]);}
 async recordUsage(runId:string,ids:number[]){for(const id of new Set(ids))await this.db.query("INSERT INTO artifact_usages(run_kind,run_id,version_id) VALUES('turn',$1,$2) ON CONFLICT DO NOTHING",[runId,id]);}
}
const rowSkill=(r:Record<string,unknown>):PublishedSkill=>({slug:String(r.slug),versionId:Number(r.version_id),version:Number(r.version),checksum:String(r.checksum??""),body:r.body,ownerId:r.owner_user_id==null?null:Number(r.owner_user_id),status:String(r.status??"active"),score:r.score==null?undefined:Number(r.score)});
export function createClassifierReranker(call:(request:{model:string;response_format:{type:string;json_schema:unknown};candidates:Array<{id:string;purpose:string;applicability:string}>})=>Promise<string>){return async(candidates:Array<{id:string;purpose:string;applicability:string}>)=>{const known=new Set(candidates.map(c=>c.id));const schema={type:"object",additionalProperties:false,required:["ids","confidence"],properties:{ids:{type:"array",uniqueItems:true,items:{type:"string",enum:[...known]}},confidence:{type:"number",minimum:0,maximum:1}}};const raw=await call({model:"eva/classifier",response_format:{type:"json_schema",json_schema:schema},candidates});let x:unknown;try{x=JSON.parse(raw)}catch{throw new Error("classifier strict JSON invalid")}if(!x||typeof x!=="object"||Array.isArray(x)||Object.keys(x).some(k=>!(["ids","confidence"].includes(k))))throw new Error("classifier strict JSON schema invalid");const v=x as {ids?:unknown;confidence?:unknown};if(!Array.isArray(v.ids)||v.ids.length===0||new Set(v.ids).size!==v.ids.length||v.ids.some(id=>typeof id!=="string"||!known.has(id))||typeof v.confidence!=="number"||v.confidence<0||v.confidence>1)throw new Error("classifier strict JSON schema invalid");return v.ids as string[];};}
