import assert from "node:assert/strict";
import { test } from "node:test";
import { AgentJobRunner } from "../dist/jobs/agent-job.js";
import { RuntimeContextBuilder } from "../dist/runtime/runtime-context.js";
import { extractRoutingMarker } from "../dist/router/routing-marker.js";

const logger={info(){},warn(){},error(){},debug(){}};
const row={user_id:"7",telegram_id:"70",language_code:"en",language_mode:"fixed",preferred_language:"en",last_message_language:"en",timezone:"UTC",city:"Secret city",country_code:"GB",agent_id:"a",conversation_id:"job-c",purpose:"maintenance",response_mode:"text",use_emoji:true,communication_style:"Secret style",profile_field_key:"name",profile_title:"Name",profile_prompt_hint:"Secret profile",profile_status:"missing",active_goal_title:"Secret goal",next_result_title:"Secret result",next_action:"Secret action",llm_quality_mode:"auto"};
function db(persisted:any[]=[]){return {query:async(sql:string)=>sql.includes("SELECT")?{rows:[row]}:(persisted.push({sql}),{rows:[]}),withUserScope:async(_x:any,fn:any)=>fn(),withSystemScope:async(_x:any,fn:any)=>fn()} as any}
function runner(letta:any,persisted:any[]=[]){const context=new RuntimeContextBuilder(db(persisted),{defaultTimezone:"UTC",routingMarkerSecret:"secret"});return new AgentJobRunner(db(persisted),letta,{ensure:async()=>({conversationId:"job-c"})} as any,context,logger as any,true)}
const input=(over:any={})=>({runId:"r1",userId:7,agentId:"a",parentConversationId:"p",signal:new AbortController().signal,spec:{jobType:"subagent_memory_reflection",purpose:"maintenance",budget:{maxInputTokens:100,maxOutputTokens:100,maxDurationMs:100,maxCostMicros:100},instruction:"reflect",resultKinds:["memory_reflection"],allowedTools:[],memoryScopes:["highlights","evidence"],modelPolicy:"quality"},...over});

test("empty registry tool allowlist reaches Letta execution boundary and rejects emitted tool without side effect",async()=>{let sideEffects=0;let options:any;const letta={runTurn:async(_c:string,_p:string,o:any)=>{options=o;const decision=await o.canUseTool("delete_notes",{});if(decision.behavior==="allow")sideEffects++;throw Object.assign(new Error("denied"),{name:"ToolDenied"})},abortTurn:async()=>({aborted:true})};const result=await runner(letta).run(input() as any);assert.equal(options.allowedTools.length,0);assert.equal(sideEffects,0);assert.equal(result.status,"failed")});

test("registry quality policy is signed into the canonical router request marker",async()=>{let prompt="";const letta={runTurn:async(_c:string,p:string)=>{prompt=p;return{reply:'{"kind":"memory_reflection","empty":true,"confidence":1,"items":[]}',usage:{},toolCalls:[]}}};await runner(letta).run(input() as any);const routed=extractRoutingMarker(prompt,"secret");assert.equal(routed.claims?.user_mode,"quality");assert.equal(routed.claims?.purpose,"maintenance")});

test("registry deadline actively aborts a hung Letta turn and persists bounded timeout failure",async()=>{let aborted=false;const persisted:any[]=[];const letta={runTurn:async()=>await new Promise(()=>{}),abortTurn:async()=>{aborted=true;return{aborted:true}}};const started=Date.now();const result=await runner(letta,persisted).run(input({spec:{...input().spec,budget:{...input().spec.budget,maxDurationMs:25}}}) as any);assert.equal(result.status,"failed");assert.equal((result as any).code,"agent_job_timeout");assert.equal(aborted,true);assert.ok(Date.now()-started<250);assert.ok(persisted.length>0)});

test("nonempty memory scopes include only highlights/evidence and exclude profile goals and task context",async()=>{const context=new RuntimeContextBuilder(db(),{defaultTimezone:"UTC",profileCompletionEnabled:true,vectorGoalsEnabled:true});(context as any).taskEvents={contextLines:async()=>["Secret task"]};const built=await context.build({userId:7,conversationId:"job-c",userMessage:"x",relevantMemory:["highlight:h1","evidence:e1","persona:secret"],memoryScopes:["highlights","evidence"]});const prompt=context.wrapUserMessage(built,"x");assert.match(prompt,/highlight:h1/);assert.match(prompt,/evidence:e1/);for(const secret of ["Secret profile","Secret goal","Secret result","Secret action","Secret task","Secret style","Secret city","persona:secret"])assert.equal(prompt.includes(secret),false,secret)});
