import assert from "node:assert/strict";import {test} from "node:test";import {SUBAGENTS,SubagentCoordinator,reflectionIntent,reflectionTrigger} from "../dist/subagents/index.js";import {EpisodeTracker} from "../dist/memory/episodes.js";
const context={kind:"job_runtime",parentKind:"interactive",tenantUserId:7,attempt:1} as const;const base={userId:7,agentId:"a",parentConversationId:"c",messageRefs:["m1"],memoryScopes:["highlights"],context};
test("registry is closed and recursion is denied by trusted context",async()=>{assert.equal(Object.keys(SUBAGENTS).length,7);const c=new SubagentCoordinator({run:async()=>({status:"empty",usage:{tokens:0,durationMs:0,costMicros:0}})} as never);await assert.rejects(c.run("arbitrary" as never,base as never,new AbortController().signal),/not allowed/);await assert.rejects(c.run("memory_reflection",{...base,context:{...context,parentKind:"subagent" as never}},new AbortController().signal),/recursive/)});
test("tenant scope, memory and tools are denied before canonical runner",async()=>{let calls=0;const c=new SubagentCoordinator({run:async()=>{calls++;return{} as never}} as never);for(const input of [{...base,context:{...context,tenantUserId:8}},{...base,memoryScopes:["persona"]},{...base,requestedTools:["delete_notes"]}])await assert.rejects(c.run("memory_reflection",input as never,new AbortController().signal));assert.equal(calls,0)});
test("public result has only schema fields and no trace",async()=>{const c=new SubagentCoordinator({run:async()=>({status:"succeeded",proposal:{kind:"memory_reflection",empty:false,confidence:1,items:[{kind:"fact",ref:"e1",summary:"x",confidence:1}]},usage:{tokens:12,durationMs:3,costMicros:4}})} as never);const result=await c.run("memory_reflection",base,new AbortController().signal);assert.deepEqual(Object.keys(result),["status","result","evidence","warnings","cost"]);assert.equal("trace" in result,false)});
test("reflection intent uses durable keep-last dedup and restricted payload",()=>{const intent=reflectionIntent({userId:7,conversationId:"c",episodeId:9,traceId:"t"});assert.equal(intent.dedupMode,"keep_last_if_active");assert.equal(intent.privacy,"restricted");assert.equal(intent.userId,7)});
test("reflection triggers on episode or 8-15 substantive messages, not simple messages",()=>{assert.equal(reflectionTrigger({episodeCompleted:false,substantiveMessages:7,simple:true}),false);assert.equal(reflectionTrigger({episodeCompleted:false,substantiveMessages:8,simple:false}),true);assert.equal(reflectionTrigger({episodeCompleted:true,substantiveMessages:2,simple:false}),true)});
test("production tracker closes at eight substantive messages through canonical callback",async()=>{const closed:unknown[]=[];let closeInput:unknown;const tracker=new EpisodeTracker(({active:true,close:async(input:unknown)=>{closeInput=input;return{id:9,conversationId:"c",messageIds:[],boundaryReason:"turn_completed"}}}) as never,async (episode:unknown)=>{closed.push(episode)});for(let i=0;i<8;i++)tracker.observe({userId:7,conversationId:"c",signal:{kind:"message",text:"This is a sufficiently substantive message about goals and progress",messageId:String(i),at:new Date(i)}});await new Promise(resolve=>setImmediate(resolve));assert.equal(closed.length,1);assert.equal((closeInput as {boundaryReason:string}).boundaryReason,"turn_completed");assert.deepEqual((closeInput as {messageIds:string[]}).messageIds,["0","1","2","3","4","5","6","7"])});
test("simple acknowledgements do not advance production threshold",async()=>{let closes=0;const tracker=new EpisodeTracker({active:true,close:async()=>{closes++;return null}} as never,async()=>{});for(let i=0;i<15;i++)tracker.observe({userId:7,conversationId:"c",signal:{kind:"message",text:"ok",messageId:String(i),at:new Date(i)}});await new Promise(resolve=>setImmediate(resolve));assert.equal(closes,0)});
